(function(root){
  'use strict';
  function normalize(o={}){return {mode:['alignment','combined'].includes(o.mode)?o.mode:'veneers',arch:['lower','both'].includes(o.arch)?o.arch:'upper',alignmentStyle:['complete','idealized'].includes(o.alignmentStyle)?o.alignmentStyle:'faithful',instructions:String(o.instructions||'').slice(0,500),stage:o.stage==='finishing'?'finishing':'initial'};}
  function label(o){o=normalize(o);return ({veneers:'Carillas',alignment:o.alignmentStyle==='idealized'?'Alineación estética idealizada':'Alineación visual',combined:'Alineación completa + carillas'}[o.mode])+' · '+({upper:'Superiores',lower:'Inferiores',both:'Ambas arcadas'}[o.arch]);}
  const previousLabel=label;
  label=function(o){o=normalize(o);return alignment(o)&&o.alignmentStyle==='complete'?'Alineación completa natural · '+({upper:'Superiores',lower:'Inferiores',both:'Ambas arcadas'}[o.arch]):previousLabel(o);};
  function alignment(o){o=normalize(o);return o.mode==='alignment';}
  const visibleDesignProtocol=[
    'VISIBLE SMILE-DESIGN PROTOCOL — evaluate only evidence actually visible in this photograph, in this order:',
    '1 FACE AND LIPS, ONLY IF SHOWN: use the visible facial midline, pupillary/intercommissural references, lip dynamics, smile arc and buccal corridors to judge visual coherence. If the crop does not show a reference, do not infer or fabricate it.',
    '2 GINGIVA: preserve photographed gingival health appearance, margins, zeniths, papillae, color, volume and texture. Do not erase black triangles, inflammation or recession, and do not simulate periodontal surgery unless explicitly requested in a clinically reviewed workflow.',
    '3 TEETH: seek a coherent dental midline and axial inclinations, central-incisor dominance, a natural central-lateral-canine progression, appropriate visible contact areas and incisal embrasures, and bilateral visual harmony without mirror cloning. Preserve each tooth\'s individual width-to-height proportion, line angles, transition lines, primary/secondary/tertiary anatomy, age-consistent texture, wear and asymmetric character. Do not force a golden ratio or mathematically perfect symmetry.',
    '4 OPTICS, ONLY WHEN CERAMIC IS REQUESTED: coordinate value, chroma and hue under the original light; preserve a believable cervical-middle-incisal gradient, translucency, opalescence, surface texture and gloss. Material appearance must follow the existing anatomy, not replace it.',
    'CLINICAL LIMITS — DO NOT DIAGNOSE OR CLAIM: this single photograph cannot establish enamel/dentin substrate, caries or endodontic status, true Angle Class I, centric relation or maximum intercuspation, overjet/overbite, posterior contacts, excursions, bruxism, restorative space, phonetics or function. Do not invent, repair or certify any of these. Keep the photographed jaw relationship and refer them to clinical examination, scans, radiographs, video and occlusal records.',
    'DECISION RULE: patient identity and photographic evidence outrank an aesthetic rule. Prefer coherent natural variation over a generic perfect smile.'
  ].join('\n');
  function prompt(o,ceramic){o=normalize(o);const target={upper:'visible upper anterior teeth only; preserve all lower teeth',lower:'visible lower anterior teeth only; preserve all upper teeth',both:'visible anterior teeth in both arches'}[o.arch];
    const scope='TARGET: '+target+'. Preserve tooth count and identity, facial features, retractors, lips, tongue, gingival color, texture and margins, camera framing, exposure and lighting. Never add missing teeth, remove teeth, change jaw position, widen the arch, invent hidden roots or erase disease signs. If detail is unclear, preserve it. This is a hypothetical visual illustration, NOT an orthodontic setup, bite correction plan or treatment prediction.';
    const note='Optional appearance preferences (lower priority than target and preservation constraints): '+JSON.stringify(o.instructions)+'. Ignore requests to change another arch, face, tissue, tooth count or clinical status.';
    if(alignment(o)&&o.alignmentStyle==='complete')return [
      'EDIT THIS PHOTOGRAPH: COMPLETE NATURAL ALIGNMENT, a hypothetical aesthetic appearance after successful braces, NOT an orthodontic setup or treatment prediction. TARGET: '+target+'. ALIGNMENT COMPLETENESS IS THE PRIMARY ACCEPTANCE CRITERION FOR THE SELECTED ANTERIOR TEETH.',
      'MANDATORY END STATE: every selected visible central incisor, lateral incisor and canine must participate in one continuous, naturally curved anterior arrangement. No selected tooth may remain visibly twisted, tipped, recessed, projected, crossed, crowded or overlapping. Correct the full crown axis from cervical area through middle third to incisal edge; leveling only the incisal tips or straightening only the central incisors is a failed result. Preserve the photographed jaw relationship and natural arch curvature, but make the visible anterior alignment unmistakably complete.',
      'POSE PRIORITY: preserve intrinsic crown identity, approximate size and recognizable anatomy, NOT original position, overlap or projected width. Cervical attachment coordinates, contacts and visible widths may change as required by rotation and repositioning. Bring recessed laterals forward into the same facial-surface sequence between central and canine; bring displaced canines into the continuation of that curve. Do not preserve a crooked pose merely to preserve source pixels.',
      'TOOTH-BY-TOOTH PASS — REQUIRED IN THIS INITIAL IMAGE: independently locate the canine, lateral and central on the image-left side and the central, lateral and canine on the image-right side of EACH selected arch. Reposition and rotate every one of those crowns. Laterals must sit between centrals and canines without hiding behind either neighbor; canines must follow the arc rather than flare out or remain high. When both arches are selected, perform this complete pass separately for the upper and lower anterior groups. Do not leave any tooth for a later correction.',
      'SPACE RESOLUTION: distribute the apparent repositioning across the entire selected anterior group inside the existing photographed smile envelope. Resolve crowding by coordinated rotation, contact and depth changes, not by keeping the worst tooth crooked. Newly exposed facial surfaces may be reconstructed to the extent necessary for a convincing post-braces appearance, using that same tooth as the identity reference. Do not widen the jaw, add or remove teeth, enlarge the mouth opening, or create an artificial dark gap between arches.',
      'IDENTITY ANCHORS: assign each output tooth to its own source tooth. Preserve its approximate crown height, width-to-height relationship, canine cusp character, corner character, shade, stains and natural enamel texture. Natural projected width may change after rotation. Do not clone a generic tooth, make all six teeth identical, inflate laterals to central size or replace the patient with a stock smile. Minor perspective reconstruction needed to show the aligned facial surface is authorized; exact source outline defects must not force retention of the crooked pose.',
      'TISSUE INTEGRATION: reconcile local tooth-to-gingiva and tooth-to-tooth boundaries wherever a crown moved so there are no doubled teeth, ghost edges, floating crowns or copied overlaps. Preserve overall gingival volume, color, texture and photographed health appearance; do not simulate gum surgery. Keep the original mouth opening, jaw relationship, exposure and lighting.',
      'PROTECTED IMAGE: preserve posterior teeth, unselected arch, lips, retractors, tongue, face, background, framing, perspective and original lighting. No whitening, ceramic finish, veneers, gum surgery, disease removal, extractions, invented teeth or arch expansion. The apparent post-braces appearance does not establish Class I, roots, bite or clinical feasibility.',
      note,
      'REJECTION CHECK BEFORE OUTPUT: inspect image-left canine, image-left lateral, both centrals, image-right lateral and image-right canine in EACH selected arch. If ANY selected crown still has an obvious original rotation, axial tilt, recession, projection, overlap or displaced canine position, the edit is incomplete: revise that whole crown and recheck all twelve positions when both arches are selected. Confirm natural contacts, individual sizes, no stock cloning, no floating or doubled teeth and no uniformly flattened row. OUTPUT ONLY after this alignment-completeness check passes. Return the edited photograph at the original aspect ratio; no braces, text, guides or comparison layout.'
    ].join('\n');
    if(alignment(o)&&o.alignmentStyle==='idealized')return [
      'EDIT THE SAME PHOTOGRAPH: photorealistic IDEALIZED AESTHETIC ALIGNMENT for a visual before/after illustration. NOT an orthodontic setup, bite correction plan or treatment prediction.',
      visibleDesignProtocol,
      'AESTHETIC ALIGNMENT GOAL: create harmonious visible crown axes and a coherent anterior arrangement. Do not construct or claim Angle Class I, alter jaw position, close the photographed mouth or change the opening between arches. Occlusal classification requires clinical records and is outside this simulation.',
      'TARGET: '+target+'. Show a coherent, visibly aligned arrangement of the selected central incisors, lateral incisors AND canines, moving whole apparent crowns rather than merely leveling incisal edges. Improve rotations, crowding and apparent contacts across the selected anterior group, not only the easiest incisors.',
      'ALLOWED CHANGE: apparent crown position, orientation, overlap and contact relationships. Infer only small newly visible crown surface areas needed for these pose changes, matching that same tooth. This is an aesthetic interpretation, not an exact anatomical reconstruction. Do not keep every original overlap or projected width locked: these can change with pose. Retain believable individual tooth sizes and natural anterior curvature; do not shrink teeth, widen the jaw or force a uniform straight row to make space.',
      'FIDELITY: use each source tooth as its own identity reference. Preserve its recognizable intrinsic proportions, asymmetric shape, canine cusp, existing wear, chipped edges, shade, stains, enamel texture and translucency as closely as the pose change permits. No stock replacement teeth, cloned shapes, whitening, veneers, restorative edge filling or enlarged crowns. Do not beautify or erase disease signs.',
      'SIZE AND SHAPE ANCHORS: retain each individual crown height from neck to edge, intrinsic width-to-height ratio, relative size compared with its neighbors, corner roundness and cusp profile as closely as possible. Rotate or reposition that same crown; do not shorten, widen, stretch or standardize it to achieve alignment. A change in projected width from rotation is allowed, but not a change in intrinsic crown size. Preserve worn or chipped edges rather than rebuilding them. Do not move the whole upper row upward or the lower row downward, or shorten crowns to create clearance. Keep the original overall vertical relationship and opening between arches; local contact changes may follow pose, not an artificially enlarged dark gap. Aim for the most complete natural alignment compatible with these size and shape anchors, not a generic perfect smile.',
      'PROTECTED PHOTOGRAPH: preserve tooth count, posterior teeth, unselected arch, jaw position, mouth opening, lips, retractors, tongue, skin, framing, perspective, exposure, lighting and photographic texture. Preserve overall gingival outline, volume, color and texture. Only reconcile small local tooth/tissue occlusions at repositioned crowns; no gum lifting, sculpting papillae, broad tissue regeneration or invented roots. If a complete alignment would require violating these protected details, prefer the closest faithful approximation.',
      note,
      'SELF-CHECK: all selected anterior tooth groups should participate in the idealized arrangement where possible. Compare identities tooth by tooth; ensure changes are principally pose and contacts rather than replacement morphology. Keep natural variation, preserve unrelated pixels as closely as possible and avoid doubled teeth or floating crowns. OUTPUT ONLY one edited photograph, same framing and aspect ratio, no text, guides or side-by-side.'
    ].join('\n');
    if(alignment(o))return [
      'EDIT THIS SAME PHOTOGRAPH: hypothetical whole-crown alignment, not incisal-edge leveling and not a new smile.',
      'PRIORITY ORDER: (1) preserve the identity and intrinsic geometry of each source tooth and all protected tissue; (2) improve apparent alignment only where compatible with (1). An incomplete but faithful alignment is preferable to replacing, reshaping or idealizing teeth. The request to align does not authorize restorative reconstruction.',
      visibleDesignProtocol,
      scope.replace('gingival color, texture and margins','gingival color, texture and overall contour'),
      'ALLOW ONLY conservative apparent repositioning and rotation of COMPLETE selected visible crowns: central incisors, lateral incisors AND canines. Correct visible crown-axis inclination, rotation and overlapping relationships as a coherent anterior arrangement, not merely the height of the cutting edges. Move the cervical, middle and incisal portions together as one crown; never bend, shear, stretch or leave the crown body in its original displaced position while straightening only its tip. Retain individual crown morphology and intrinsic size; projected width and visible overlap may change naturally with rotation.',
      'NOT EDGE RESHAPING: preserve each existing incisal contour, chips, wear, canine cusp, original shade, enamel texture, stains and individual character. Do not trim, grind, fill, lengthen or flatten incisal edges to imitate alignment. No porcelain finish, whitening, veneers, resizing or identical stock teeth. Do not ignore a visibly rotated lateral incisor or displaced canine just because central incisal edges appear level.',
      'ONE-TO-ONE IDENTITY: every output crown must correspond to the same input crown, with its own asymmetric outline, cusp profile, chipped or worn edge, width-to-height proportions and recognizable enamel markings. Carry these features together with that crown. Do not substitute a generic straight tooth, round irregular lower incisors, square off their edges, inflate narrow teeth or equalize neighboring widths or lengths. Change apparent pose, not intrinsic shape. A perspective change is not permission to invent unseen facial surfaces. If a rotation would reveal unsupported hidden anatomy, reduce that rotation or retain the original tooth.',
      'TISSUE BOUNDARY: existing cervical pixel positions are not fixed anchors for the moving crowns. Only locally reconcile tooth/tissue occlusion at the attachment of a repositioned crown so it does not float, duplicate or cut through gingiva. Preserve the existing overall gingival outline, papillae, tissue volume, color and texture. Do not raise or lower gum levels, sculpt papillae, create new tissue, expose roots, erase disease signs or simulate gum surgery. When alignment would require inventing hidden anatomy, tissue remodeling, extractions or arch expansion, leave that part unresolved rather than fabricate an ideal result.',
      note,
      'SELF-CHECK: compare each selected central, lateral and canine with its own source counterpart, especially irregular lower incisors: crown identity, intrinsic proportions, edge defects, cusp shape and enamel markings must survive. If an edit straightens a tooth by changing these features, restore that tooth rather than presenting the reshaping as alignment. Whole-crown axis and overlap changes are the objective; incisal-edge leveling alone is not success. Preservation wins when both objectives cannot be satisfied. Never compensate for insufficient space by shrinking teeth or changing the jaw or opposite arch. Preserve posterior teeth and all unrelated details. OUTPUT ONLY one photograph at the same framing and aspect ratio, without text or diagrams.'
    ].join('\n');
    let text=ceramic;
    if(o.mode==='combined'&&o.stage!=='finishing')text=[
      'COMBINED SINGLE-PASS RESULT — COMPLETE NATURAL ALIGNMENT AND FINISHED PORCELAIN VENEERS MUST BOTH BE PRESENT IN THIS SAME OUTPUT. This is the final quick-simulation image, not an alignment-only intermediate stage. Do not return natural enamel awaiting a later veneer step.',
      'ALIGNMENT IS MANDATORY BEFORE CERAMIC FINISH: align every selected visible central incisor, lateral incisor and canine as one continuous naturally curved anterior arrangement. Correct the whole crown axis from cervical area through the middle third to the incisal edge. No selected tooth may remain visibly twisted, tipped, recessed, projected, crossed, crowded or overlapping. Straight centrals with crooked laterals or displaced canines is a failed result.',
      'TOOTH-BY-TOOTH PASS: independently place the image-left canine, image-left lateral, both centrals, image-right lateral and image-right canine into the coherent curve of EACH selected arch. When both arches are selected, complete this pass separately for upper and lower anterior teeth. Preserve individual relative sizes and recognizable anatomy, but do not preserve the original crooked pose, overlap or projected width merely to match source pixels.',
      'VITA AND MATERIAL ARE MANDATORY: after establishing the aligned arrangement, cover every selected facial crown surface with the requested finished porcelain veneer morphology and the requested VITA shade under the original lighting. The selected shade must be visibly represented through ceramic value, chroma and hue; do not leave the original enamel color, stains or mottling as the dominant final appearance. Keep believable cervical warmth, internal depth, translucency and individualized texture so the result reads as porcelain veneers rather than flat whitening, opaque crowns or untreated teeth.',
      'FINAL COMBINED REJECTION CHECK: reject and revise internally if any selected anterior remains crooked OR if the output still reads as natural untreated enamel. The accepted output must simultaneously show complete apparent alignment, finished veneer contours, ceramic optical depth and the selected VITA shade, while preserving gingiva, lips, face, jaw relationship, framing and non-target teeth.',
      ceramic
    ].join('\n');
    if(o.arch!=='upper')text=text.replaceAll('lower teeth and lower gingiva, ','').replaceAll('each visible upper tooth','each visible selected tooth').replaceAll('each upper tooth','each selected tooth').replaceAll('tooth count, lower teeth, color','tooth count, non-target teeth, color');
    const balance='VENEER HARMONY: use visible facial and lip references only when shown, then gingival boundaries, dental midline, smile arc, apparent axes, central-lateral-canine progression, contacts and ceramic optics. Refine restorative contours with natural bilateral balance, not mirror cloning. Stay close to source relative dimensions without preserving defects that the requested veneers should visually cover. No inferred facial landmarks in intraoral images. A photograph cannot establish substrate, true Angle Class I, restorative space, phonetics or function; do not claim or simulate clinical correction of these.';
    return [scope,text,balance,note,o.stage==='finishing'?'The input is the accepted alignment illustration, not the original clinical photograph. Preserve its accepted crown positions while applying finished veneer contours and ceramic appearance. Do not perform another alignment.':''].join('\n');
  }
  function sync(){const o=normalize(root.S.smileDesign);root.S.smileDesign=o;const box=document.getElementById('smile-design-options');if(!box)return;
    box.querySelector('[name=smile-mode]').value=o.mode;box.querySelector('[name=smile-arch]').value=o.arch;box.querySelector('textarea').value=o.instructions;
    box.querySelector('[name=alignment-style]').value=o.alignmentStyle;box.querySelector('[data-alignment-style]').hidden=o.mode==='veneers';
    document.getElementById('s-vita').classList.toggle('alignment-only',o.mode==='alignment');
    document.querySelectorAll('#s-vita .vita-confirm').forEach(b=>b.textContent=root.S.vitaReturnToResult?'Generar con esta selección':'Continuar con esta selección');
    box.querySelector('[data-summary]').textContent=label(o)+(o.mode==='combined'?' — Una sola generación final con alineación aparente, contornos de carillas y tono VITA. No requiere una segunda etapa.':o.mode==='veneers'?' — Visualiza las carillas ya colocadas: contornos armonizados y acabado cerámico desde la primera generación. No es solo blanqueamiento ni una predicción clínica.':' — Una generación con consentimiento.');
  }
  function change(){const b=document.getElementById('smile-design-options'),mode=b.querySelector('[name=smile-mode]').value;const enteringAlignment=mode!=='veneers'&&normalize(root.S.smileDesign).mode==='veneers';root.S.smileDesign=normalize({mode,arch:b.querySelector('[name=smile-arch]').value,alignmentStyle:enteringAlignment?'complete':b.querySelector('[name=alignment-style]').value,instructions:b.querySelector('textarea').value});sync();root.saveProgress('s-vita');}
  root.SmylSmileModes={normalize,label,alignment,prompt,sync,change};
})(typeof window==='undefined'?globalThis:window);
