import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync('simulacion-rapida.html','utf8');
const c={URL,URLSearchParams};vm.createContext(c);vm.runInContext(fs.readFileSync('lana-quick-bridge.js','utf8'),c);
const bridge=c.SmylLanaQuick;
const tenant='11111111-1111-4111-8111-111111111111';
const storage={getItem:()=>JSON.stringify({tenant_id:tenant,cita_id:5,paciente:'Persona de prueba',telefono:'+523300000000',origen:'lana'})};
const cfg={tenantId:tenant,userToken:'test-only',supaKey:'public',supaUrl:'https://example.invalid'};
assert.equal(bridge.bind(cfg,storage,'?origen=lana').citaId,5);
assert.equal(bridge.bind({...cfg,userToken:null},storage,'?origen=lana'),null);
assert.equal(bridge.bind({...cfg,modoProspecto:true},storage,'?origen=lana'),null);
assert.throws(()=>bridge.bind({...cfg,tenantId:'other'},storage,'?origen=lana'),/otra clínica/);
assert.equal(bridge.read({getItem:()=>'{'}),null);
let calls=0;
const fetcher=async(url,request)=>{calls++;assert.equal(JSON.parse(request.body).simulacion_id,'case');assert.equal(request.headers.Authorization,'Bearer test-only');return {ok:true,json:async()=>({ok:true})};};
await assert.rejects(bridge.notify(cfg,{id:'case'},fetcher,'http://localhost/'),/HTTPS/);assert.equal(calls,0);
await bridge.notify(cfg,{id:'case'},fetcher,'https://smyl.example/simulacion-rapida.html');assert.equal(calls,1);
await assert.rejects(bridge.notify(cfg,{id:'case'},async()=>({ok:true,json:async()=>({ok:false})}),'https://smyl.example/'),/confirmó/);
assert.match(html,/savedToCloud&&CFG.lanaContext/);
assert.match(html,/lana_cita_id: casoData.lana_cita_id/);
assert.match(html,/CFG.lanaContext=null/);
assert.match(html,/SmylLanaQuick.showStatus/);
assert.match(html,/centroY<\.40/);
assert.match(html,/app-safe-notice-action/);
assert.match(html,/function aplicarTonoDesdeResultado\(\)/);
assert.match(html,/nunca se aplica[\s\S]*filtro local/);
assert.match(html,/veneerBaseByView: S\.veneerBaseByView/);
assert.match(html,/S\.veneerBaseByView = snap\.veneerBaseByView \|\| \{\}/);
assert.match(html,/Cargar paciente sintético · 6 fotos/);
assert.match(html,/SMYL_SYNTHETIC_TEST_CASE/);
assert.match(html,/S\.testDatasetLoaded=false;await processPhotos\(\)/);
assert.match(html,/Probar frontal \+ intraoral/);
assert.match(html,/SMYL_SYNTHETIC_PAIRED_CASE/);
assert.match(html,/reason:'diseno_maestro_intraoral'/);
assert.match(html,/S\.veneerBaseByView\.intraoral=resultadoIntraoral/);
assert.match(html,/async function localizarBocaEnFotografia/);
assert.match(html,/S\.landmarker\.detectForVideo\(img, performance\.now\(\)\)/);
assert.match(html,/mouthRegion: mouthRegion/);
assert.match(html,/bandaArcadasDesdeBoca\(c,input\.mouthRegion\)/);
assert.match(html,/prepared\.localizerVersion='face-mouth-v1'/);
const mouthLandmarks=Array.from({length:478},()=>({x:.5,y:.53}));
[61,146,91,181,84,17,314,405,321,375,291,185,40,39,37,0,267,269,270,409,78,95,88,178,87,14,317,402,318,324,308,191,80,81,82,13,312,311,310,415].forEach((index,i)=>{
  mouthLandmarks[index]={x:i%2?.66:.34,y:i%3?.58:.47};
});
const locatorContext={S:{landmarker:{detectForVideo:()=>({faceLandmarks:[mouthLandmarks]})}},initFaceLandmarker:async()=>true,performance,setTimeout,console};
vm.createContext(locatorContext);
vm.runInContext(html.slice(html.indexOf('async function localizarBocaEnFotografia'),html.indexOf('// Un único cálculo compartido')),locatorContext);
vm.runInContext(html.slice(html.indexOf('function calcularRectRecorteDental'),html.indexOf('// Gemini genera mucho mejor anatomía')),locatorContext);
const locatedMouth=await locatorContext.localizarBocaEnFotografia({},'frontal');
assert.equal(locatedMouth.source,'face-landmarks');
const autoCrop=locatorContext.calcularRectRecorteDental(1200,1600,'frontal',locatedMouth);
assert.ok(autoCrop.x < locatedMouth.x*1200 && autoCrop.x+autoCrop.w > (locatedMouth.x+locatedMouth.w)*1200);
assert.ok(autoCrop.y < locatedMouth.y*1600 && autoCrop.y+autoCrop.h > (locatedMouth.y+locatedMouth.h)*1600);
assert.equal(locatorContext.calcularRectRecorteDental(1200,1600,'intraoral',locatedMouth).isFull,true);
for(const file of ['01-frontal-sonrisa.png','02-perfil-derecho.png','03-perfil-izquierdo.png','04-vista-3-4.png','05-intraoral-dientes.png','06-extraoral-rostro.png'])assert.equal(fs.existsSync('demo/smyl-paciente-chuecos-v1/'+file),true);
for(const file of ['01-frontal-rostro.png','02-intraoral-frontal.png'])assert.equal(fs.existsSync('demo/smyl-paciente-chuecos-v2/'+file),true);
assert.doesNotMatch(html.slice(html.indexOf('async function elegirTonoDesdeResultado'),html.indexOf('async function elegirTonoActualDesdeResultado')),/recolorearDientes\(/);
for(const [,script] of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)){if(script.trim())new vm.Script(script);}
for(const file of ['simulacion-rapida.html','app.html','lana-quick-bridge.js','visual-simulation.js','smile-modes.js','visual-composition.js','visual-simulation.css'])assert.equal(fs.readFileSync(file,'utf8'),fs.readFileSync('mobile/www/'+file,'utf8'));
const p={};vm.createContext(p);for(const file of ['smile-modes.js','visual-simulation.js'])vm.runInContext(fs.readFileSync(file,'utf8'),p);
assert.match(p.SmylVisualSimulation.prompt({mode:'veneers',construction:'layered'}),/VENEER OPTICAL INTEGRATION/);
assert.match(p.SmylVisualSimulation.prompt({mode:'veneers',construction:'layered'}),/CERAMIC CONSTRUCTION — LAYERED/);
assert.match(p.SmylVisualSimulation.prompt({mode:'veneers',construction:'layered'}),/CENTRAL INCISAL FINISH — TEETH 11 AND 21/);
assert.match(p.SmylVisualSimulation.prompt({mode:'veneers',construction:'layered'}),/Remove source chips, notches, serrations/);
const completeAlignment=p.SmylVisualSimulation.prompt({mode:'alignment',arch:'both',alignmentStyle:'complete',stage:'initial'});
assert.match(completeAlignment,/ALIGNMENT COMPLETENESS IS THE PRIMARY ACCEPTANCE CRITERION/);
assert.match(completeAlignment,/No selected tooth may remain visibly twisted, tipped, recessed, projected, crossed, crowded or overlapping/);
assert.match(completeAlignment,/perform this complete pass separately for the upper and lower anterior groups/);
assert.match(completeAlignment,/If ANY selected crown still has an obvious original rotation/);
const combined=p.SmylVisualSimulation.prompt({mode:'combined',arch:'both',alignmentStyle:'complete',stage:'initial',shade:'A1',construction:'layered'});
assert.match(combined,/COMBINED SINGLE-PASS RESULT/);
assert.match(combined,/No selected tooth may remain visibly twisted, tipped, recessed, projected, crossed, crowded or overlapping/);
assert.match(combined,/VITA AND MATERIAL ARE MANDATORY/);
assert.match(combined,/VITA Classical A1/);
assert.match(combined,/light high-value warm ivory with restrained warm chroma/);
const c2=p.SmylVisualSimulation.prompt({mode:'combined',arch:'both',alignmentStyle:'complete',stage:'initial',shade:'C2',construction:'layered'});
assert.match(c2,/medium-value, low-chroma neutral gray ivory/);
assert.match(c2,/distinctly less luminous, less warm and more muted than A1/);
assert.match(c2,/Do not collapse different VITA codes into the same generic cream or ivory/);
const lockedShade=p.SmylVisualSimulation.prompt({mode:'combined',arch:'both',alignmentStyle:'complete',stage:'initial',shade:'B2',construction:'layered',materialOnly:true,baseShade:'A1'});
assert.match(lockedShade,/MATERIAL-ONLY VITA OVERRIDE — HIGHEST PRIORITY/);
assert.match(lockedShade,/Pixel-lock every crown silhouette/);
assert.match(lockedShade,/This override cancels any morphology, alignment or contour instruction/);
assert.match(lockedShade,/centrals turn gray while adjacent teeth turn yellow/);
assert.match(combined,/upper and lower veneers must share the same VITA family and value/);
assert.match(combined,/correct any blue-gray lower arch/);
assert.match(combined,/CERAMIC CONSTRUCTION — LAYERED/);
console.log('Quick/LANA: tenant isolation, professional session, local send block, confirmed delivery, scripts and mobile parity pass.');
let cloudOK=true,notified=0,lastCase;
const field={value:'Prueba sintética',style:{},focus(){}};
Object.assign(c,{CFG:cfg,S:{diagnosis:{},photos:[],results:{frontal:'https://example.invalid/result'},casoId:'case'},document:{getElementById:()=>field},localStorage:{getItem:()=>null,setItem(){}},generarUuid:()=> 'case',clearProgress(){},showCasoGuardado:value=>lastCase=value,console,fetch:async()=>({ok:cloudOK,status:cloudOK?201:500,text:async()=> 'mock failure'}),SmylLanaQuick:{notify:async()=>{notified++;return {ok:true};},showStatus(){}},location:{href:'https://smyl.example/'}});
vm.runInContext(html.slice(html.indexOf('async function guardarCaso()'),html.indexOf('function showCasoGuardado(')),c);
await c.guardarCaso();assert.equal(notified,1);assert.equal(lastCase.lana_sincronizado,true);assert.equal(lastCase.lana_cita_id,5);
cloudOK=false;await c.guardarCaso();assert.equal(notified,1);
console.log('Actual quick save: cloud confirmation precedes LANA delivery; failed save does not notify.');
