import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../simulacion-rapida.html',import.meta.url),'utf8');
const source=html.slice(html.indexOf('var referenciaOpcionalCargando='),html.indexOf('function actualizarCargaParPropio()'));
const elements=new Map();
const document={getElementById(id){if(!elements.has(id))elements.set(id,{removeAttribute(name){delete this[name];}});return elements.get(id);},querySelectorAll(){return [{disabled:false}];}};
const state={photos:[{view:'frontal',b64:'original'}]};
const ctx=vm.createContext({S:state,document,leerFotoPropia:async()=> 'local',redimensionarFotoB64:async()=> 'reference',saveProgress(){},mostrarAvisoAplicacion(){}});
vm.runInContext(source,ctx);
const input={files:[{size:100,type:'image/png',name:'test.png'}],value:'selected'};
await ctx.cargarReferenciaOpcional(input);
assert.equal(state.photos.length,2);
assert.equal(state.photos[0].b64,'original');
assert.equal(state.photos[1].view,'intraoral');
assert.equal(document.getElementById('quick-reference-preview').hidden,false);
await ctx.cargarReferenciaOpcional(input);
assert.equal(state.photos.length,2,'replace rather than duplicate');
ctx.redimensionarFotoB64=async()=> {throw new Error('invalid');};
await ctx.cargarReferenciaOpcional(input);
assert.equal(state.photos[1].b64,'reference','failure preserves previous reference');
ctx.quitarReferenciaOpcional();
assert.equal(state.photos.length,1);
assert.equal(state.photos[0].b64,'original');
assert.equal(document.getElementById('quick-reference-preview').hidden,true);
assert.doesNotMatch(source,/fetch\(|generateSimulation\(|processPhotos\(/);
console.log('Optional intraoral: add, replace, failed decode, remove and no generation verified.');
